### ISSUE TITLE
Serial port connection fails

### ISSUE THREAD

**Issue by lekhabs243** [Martinsl/myo-sphero-opencv#1]
![stackoverflow-myo](https://cloud.githubusercontent.com/assets/8922390/15237237/d3ac39c0-1880-11e6-90ee-a982f876144e.JPG)

I'm a new bee in python and trying to run myo_raw.py for raw emg data. The code recognizes COM3 port but fails to open port. Please help me with this error.
File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 66, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

**Comment by Martinsl** [comment]
Hey, I usually use Linux for programming, so I'm not sure I can help, but  first thing you should try when getting an  'Access is denied.' error is running the CMD as administrator (or 'sudo', on Linux). Second you should check if the port is being used by another process.

**Comment by lekhabs243** [comment]
You are right about port being used by other process. I had to remove myo connect to the code .Now up and running!
